name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8' ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java }}
    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-deps-${{ hashFiles('**/deps.edn') }}
        restore-keys: |
          ${{ runner.os }}-deps-
    - uses: gleam-lang/setup-erlang@v1.1.2
      with:
        otp-version: 23.2
    - uses: actions/cache@v2
      with:
        path: ~/.cache/rebar3/hex/hexpm/packages
        key: ${{ runner.os }}-hex-${{ hashFiles(format('{0}{1}', github.workspace, '/rebar.lock')) }}
        restore-keys: |
          ${{ runner.os }}-hex-
    - uses: turtlequeue/setup-babashka@v1.3.0
      with:
        babashka-version: 0.3.2
    - run: bb -m tasks/ci
    - run: bb -m tasks/app
      if: ${{ github.event_name == 'push' }}
    - uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'push' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/pwa-release/
